FROM python:3.11-slim

WORKDIR /app

# Create data folder
RUN mkdir -p /data/staging /data/processed /data/output /models /api/data

# Install system dependencies
RUN apt-get update && apt-get install -y \
    gcc \
    g++ \
    && rm -rf /var/lib/apt/lists/*

# Copy requirements.txt first for caching
COPY requirments.txt .
RUN pip install --no-cache-dir -r requirements.txt

# Download NLP models
RUN python -m spacy download en_core_web_sm
RUN python -m nltk.downloader stopwords punkt

#Copy application code
COPY src/ ./src/
COPY api/ ./api/
COPY dags/ ./dags/

# Set environment variables
ENV PYTHONPATH=/app
ENV AIRFLOW_HOME=/airflow

# Initialize Airlfow (for production, use entrypoint)
RUN airlofw df init



EXPOSE 8000 8000

CMD ['uvicorn', 'api.main:app', ''--host', '0.0.0.0', '8000']